export interface Project {
  id: string
  title: string
  type: 'image' | 'video'
  src: string
  thumbnail: string
  x: number
  y: number
  width: number
  height: number
}

// Auto-generated by scripts/ingest.mjs — do not edit manually
export const projects: Project[] = [
  {
    "id": "gucci-parralax",
    "title": "Gucci Parralax",
    "type": "video",
    "src": "/assets/motion/gucci-parralax.mp4",
    "thumbnail": "/assets/motion/thumbs/gucci-parralax.webp",
    "width": 320,
    "height": 218,
    "x": 122,
    "y": 100
  },
  {
    "id": "vertical-power-bank-v2",
    "title": "Vertical Power Bank V2",
    "type": "video",
    "src": "/assets/motion/vertical-power-bank-v2.mp4",
    "thumbnail": "/assets/motion/thumbs/vertical-power-bank-v2.webp",
    "width": 320,
    "height": 228,
    "x": 551,
    "y": 100
  },
  {
    "id": "composition-1",
    "title": "Composition 1",
    "type": "video",
    "src": "/assets/motion/composition-1.mp4",
    "thumbnail": "/assets/motion/thumbs/composition-1.webp",
    "width": 300,
    "height": 202,
    "x": 107,
    "y": 490
  },
  {
    "id": "renagde-project-24",
    "title": "Renagde Project 24",
    "type": "video",
    "src": "/assets/motion/renagde-project-24.mp4",
    "thumbnail": "/assets/motion/thumbs/renagde-project-24.webp",
    "width": 260,
    "height": 190,
    "x": 1014,
    "y": 100
  },
  {
    "id": "cible-rotate0001-0250",
    "title": "Cible Rotate0001 0250",
    "type": "video",
    "src": "/assets/motion/cible-rotate0001-0250.mp4",
    "thumbnail": "/assets/motion/thumbs/cible-rotate0001-0250.webp",
    "width": 280,
    "height": 190,
    "x": 543,
    "y": 493
  },
  {
    "id": "carte-sd_1_0001-vertical",
    "title": "Carte Sd 1 0001 Vertical",
    "type": "video",
    "src": "/assets/motion/carte-sd_1_0001-vertical.mp4",
    "thumbnail": "/assets/motion/thumbs/carte-sd_1_0001-vertical.webp",
    "width": 280,
    "height": 200,
    "x": 1401,
    "y": 129
  },
  {
    "id": "caeremonia_t-shirt-back_mockups",
    "title": "Caeremonia T Shirt Back Mockups",
    "type": "image",
    "src": "/assets/graphic/caeremonia_t-shirt-back_mockups.webp",
    "thumbnail": "/assets/graphic/caeremonia_t-shirt-back_mockups.webp",
    "width": 340,
    "height": 348,
    "x": 100,
    "y": 910
  },
  {
    "id": "caeremonia-motion",
    "title": "Caeremonia Motion",
    "type": "video",
    "src": "/assets/motion/caeremonia-motion.mp4",
    "thumbnail": "/assets/motion/thumbs/caeremonia-motion.webp",
    "width": 280,
    "height": 193,
    "x": 1008,
    "y": 483
  },
  {
    "id": "virgnies-nailique",
    "title": "Virgnies Nailique",
    "type": "image",
    "src": "/assets/graphic/virgnies-nailique.webp",
    "thumbnail": "/assets/graphic/virgnies-nailique.webp",
    "width": 340,
    "height": 385,
    "x": 1864,
    "y": 130
  },
  {
    "id": "inflate_txt_insta",
    "title": "Inflate Txt Insta",
    "type": "video",
    "src": "/assets/motion/inflate_txt_insta.mp4",
    "thumbnail": "/assets/motion/thumbs/inflate_txt_insta.webp",
    "width": 300,
    "height": 214,
    "x": 1425,
    "y": 463
  },
  {
    "id": "mockups-affiche",
    "title": "Mockups Affiche",
    "type": "image",
    "src": "/assets/graphic/mockups-affiche.webp",
    "thumbnail": "/assets/graphic/mockups-affiche.webp",
    "width": 340,
    "height": 341,
    "x": 546,
    "y": 835
  },
  {
    "id": "composition-1_1",
    "title": "Composition 1 1",
    "type": "video",
    "src": "/assets/motion/composition-1_1.mp4",
    "thumbnail": "/assets/motion/thumbs/composition-1_1.webp",
    "width": 300,
    "height": 205,
    "x": 2366,
    "y": 105
  },
  {
    "id": "cover-adam",
    "title": "Cover Adam",
    "type": "image",
    "src": "/assets/graphic/cover-adam.webp",
    "thumbnail": "/assets/graphic/cover-adam.webp",
    "width": 260,
    "height": 307,
    "x": 1008,
    "y": 802
  },
  {
    "id": "caeremonia_t-shirt-face_mockups",
    "title": "Caeremonia T Shirt Face Mockups",
    "type": "image",
    "src": "/assets/graphic/caeremonia_t-shirt-face_mockups.webp",
    "thumbnail": "/assets/graphic/caeremonia_t-shirt-face_mockups.webp",
    "width": 300,
    "height": 281,
    "x": 119,
    "y": 1411
  },
  {
    "id": "cover-adam2",
    "title": "Cover Adam2",
    "type": "image",
    "src": "/assets/graphic/cover-adam2.webp",
    "thumbnail": "/assets/graphic/cover-adam2.webp",
    "width": 340,
    "height": 339,
    "x": 1390,
    "y": 860
  },
  {
    "id": "caeremonia_hoodie_mockups",
    "title": "Caeremonia Hoodie Mockups",
    "type": "image",
    "src": "/assets/graphic/caeremonia_hoodie_mockups.webp",
    "thumbnail": "/assets/graphic/caeremonia_hoodie_mockups.webp",
    "width": 280,
    "height": 258,
    "x": 1883,
    "y": 726
  },
  {
    "id": "pp2---lnd-da25",
    "title": "Pp2   Lnd Da25",
    "type": "image",
    "src": "/assets/graphic/pp2---lnd-da25.webp",
    "thumbnail": "/assets/graphic/pp2---lnd-da25.webp",
    "width": 280,
    "height": 237,
    "x": 546,
    "y": 1324
  },
  {
    "id": "composition-finale",
    "title": "Composition Finale",
    "type": "video",
    "src": "/assets/motion/composition-finale.mp4",
    "thumbnail": "/assets/motion/thumbs/composition-finale.webp",
    "width": 260,
    "height": 196,
    "x": 2399,
    "y": 499
  },
  {
    "id": "cover-giz",
    "title": "Cover Giz",
    "type": "image",
    "src": "/assets/graphic/cover-giz.webp",
    "thumbnail": "/assets/graphic/cover-giz.webp",
    "width": 280,
    "height": 264,
    "x": 1008,
    "y": 1235
  },
  {
    "id": "motion-pfe",
    "title": "Motion Pfe",
    "type": "video",
    "src": "/assets/motion/motion-pfe.mp4",
    "thumbnail": "/assets/motion/thumbs/motion-pfe.webp",
    "width": 260,
    "height": 192,
    "x": 118,
    "y": 1890
  },
  {
    "id": "3d-higlight",
    "title": "3d Higlight",
    "type": "image",
    "src": "/assets/graphic/3d-higlight.webp",
    "thumbnail": "/assets/graphic/3d-higlight.webp",
    "width": 260,
    "height": 277,
    "x": 2309,
    "y": 798
  },
  {
    "id": "graphic-highlight",
    "title": "Graphic Highlight",
    "type": "image",
    "src": "/assets/graphic/graphic-highlight.webp",
    "thumbnail": "/assets/graphic/graphic-highlight.webp",
    "width": 300,
    "height": 351,
    "x": 570,
    "y": 1698
  },
  {
    "id": "suitecase",
    "title": "Suitecase",
    "type": "video",
    "src": "/assets/motion/suitecase.mp4",
    "thumbnail": "/assets/motion/thumbs/suitecase.webp",
    "width": 340,
    "height": 228,
    "x": 1451,
    "y": 1314
  },
  {
    "id": "booking-hero",
    "title": "Booking Hero",
    "type": "image",
    "src": "/assets/graphic/booking-hero.webp",
    "thumbnail": "/assets/graphic/booking-hero.webp",
    "width": 320,
    "height": 298,
    "x": 1004,
    "y": 1621
  },
  {
    "id": "motion-songbird-se-horizontal-v2",
    "title": "Motion Songbird Se Horizontal V2",
    "type": "video",
    "src": "/assets/motion/motion-songbird-se-horizontal-v2.mp4",
    "thumbnail": "/assets/motion/thumbs/motion-songbird-se-horizontal-v2.webp",
    "width": 340,
    "height": 223,
    "x": 118,
    "y": 2268
  },
  {
    "id": "motion-highlight",
    "title": "Motion Highlight",
    "type": "image",
    "src": "/assets/graphic/motion-highlight.webp",
    "thumbnail": "/assets/graphic/motion-highlight.webp",
    "width": 300,
    "height": 304,
    "x": 1898,
    "y": 1282
  },
  {
    "id": "logo-xyz",
    "title": "Logo Xyz",
    "type": "image",
    "src": "/assets/graphic/logo-xyz.webp",
    "thumbnail": "/assets/graphic/logo-xyz.webp",
    "width": 300,
    "height": 266,
    "x": 2686,
    "y": 798
  },
  {
    "id": "cover_template",
    "title": "Cover Template",
    "type": "image",
    "src": "/assets/graphic/cover_template.webp",
    "thumbnail": "/assets/graphic/cover_template.webp",
    "width": 260,
    "height": 256,
    "x": 1468,
    "y": 1702
  },
  {
    "id": "disc-motion-portrait",
    "title": "Disc Motion Portrait",
    "type": "video",
    "src": "/assets/motion/disc-motion-portrait.mp4",
    "thumbnail": "/assets/motion/thumbs/disc-motion-portrait.webp",
    "width": 260,
    "height": 190,
    "x": 2343,
    "y": 1228
  },
  {
    "id": "dither-tst",
    "title": "Dither Tst",
    "type": "image",
    "src": "/assets/graphic/dither-tst.webp",
    "thumbnail": "/assets/graphic/dither-tst.webp",
    "width": 260,
    "height": 306,
    "x": 570,
    "y": 2205
  },
  {
    "id": "pp_3dme25",
    "title": "Pp 3dme25",
    "type": "image",
    "src": "/assets/graphic/pp_3dme25.webp",
    "thumbnail": "/assets/graphic/pp_3dme25.webp",
    "width": 260,
    "height": 325,
    "x": 985,
    "y": 2090
  },
  {
    "id": "composition-4",
    "title": "Composition 4",
    "type": "video",
    "src": "/assets/motion/composition-4.mp4",
    "thumbnail": "/assets/motion/thumbs/composition-4.webp",
    "width": 340,
    "height": 232,
    "x": 1846,
    "y": 1716
  },
  {
    "id": "sream-starting-da-xxmms",
    "title": "Sream Starting Da Xxmms",
    "type": "video",
    "src": "/assets/motion/sream-starting-da-xxmms.mp4",
    "thumbnail": "/assets/motion/thumbs/sream-starting-da-xxmms.webp",
    "width": 300,
    "height": 201,
    "x": 138,
    "y": 2639
  },
  {
    "id": "composition-3",
    "title": "Composition 3",
    "type": "video",
    "src": "/assets/motion/composition-3.mp4",
    "thumbnail": "/assets/motion/thumbs/composition-3.webp",
    "width": 260,
    "height": 190,
    "x": 2733,
    "y": 1228
  },
  {
    "id": "dither-stinger-sounded",
    "title": "Dither Stinger Sounded",
    "type": "video",
    "src": "/assets/motion/dither-stinger-sounded.mp4",
    "thumbnail": "/assets/motion/thumbs/dither-stinger-sounded.webp",
    "width": 340,
    "height": 225,
    "x": 1355,
    "y": 2090
  },
  {
    "id": "darts-motion",
    "title": "Darts Motion",
    "type": "video",
    "src": "/assets/motion/darts-motion.mp4",
    "thumbnail": "/assets/motion/thumbs/darts-motion.webp",
    "width": 300,
    "height": 213,
    "x": 2332,
    "y": 1537
  },
  {
    "id": "lnd-da25-banner",
    "title": "Lnd Da25 Banner",
    "type": "image",
    "src": "/assets/graphic/lnd-da25-banner.webp",
    "thumbnail": "/assets/graphic/lnd-da25-banner.webp",
    "width": 320,
    "height": 274,
    "x": 556,
    "y": 2673
  },
  {
    "id": "skeleton-burning-ai-tst",
    "title": "Skeleton Burning Ai Tst",
    "type": "video",
    "src": "/assets/motion/skeleton-burning-ai-tst.mp4",
    "thumbnail": "/assets/motion/thumbs/skeleton-burning-ai-tst.webp",
    "width": 280,
    "height": 198,
    "x": 1928,
    "y": 2113
  },
  {
    "id": "suitecase_vertical",
    "title": "Suitecase Vertical",
    "type": "video",
    "src": "/assets/motion/suitecase_vertical.mp4",
    "thumbnail": "/assets/motion/thumbs/suitecase_vertical.webp",
    "width": 320,
    "height": 215,
    "x": 2332,
    "y": 1939
  },
  {
    "id": "showreel_1",
    "title": "Showreel 1",
    "type": "video",
    "src": "/assets/motion/showreel_1.mp4",
    "thumbnail": "/assets/motion/thumbs/showreel_1.webp",
    "width": 320,
    "height": 218,
    "x": 982,
    "y": 2659
  },
  {
    "id": "web-highlight",
    "title": "Web Highlight",
    "type": "image",
    "src": "/assets/graphic/web-highlight.webp",
    "thumbnail": "/assets/graphic/web-highlight.webp",
    "width": 300,
    "height": 342,
    "x": 120,
    "y": 3012
  },
  {
    "id": "3d-me-reels",
    "title": "3d Me Reels",
    "type": "video",
    "src": "/assets/motion/3d-me-reels.mp4",
    "thumbnail": "/assets/motion/thumbs/3d-me-reels.webp",
    "width": 320,
    "height": 217,
    "x": 1480,
    "y": 2537
  }
]
